---
Name: pageimages
---
# pageimages configurable parameter(s):
PageImages:
# Set a specific folder name to upload to
# Default = Uploads
#  upload_folder_name: 'Uploads'

# Set allowed extensions for images
# Default to types known by file category image
#  allowed_extensions:
#    - jpg
#    - jpeg
#    - gif
#    - png

# Set allowed maximum filesize for images
# Default = 1048576 = 1MB (1* 1024 * 1024)
#  allowed_max_file_size: 1048576

# Extend DataObject Page
Page:
  extensions:
    - PageImages

# Extend Image
Image:
  extensions:
    - PageImage

#Add some required styles to cms
LeftAndMain:
  extra_requirements_css:
    - pageimages/css/PageImages.css
