---
Name: pageimages
---
# pageimages configurable parameter(s):
PageImages:
# Set max amount of images.
# Default = 5.
#  image_count_limit: 5

# Set a specific folder name to upload to
# Default = Uploads
#  upload_folder_name: 'Uploads'

# Avoid uploading images (select existing from assets)
# Default = true
#  can_upload: true

# Set allowed extensions for images
# Default to types known by file category image
#  allowed_extensions:
#    - jpg
#    - jpeg
#    - gif
#    - png

# Set allowed maximum filesize for images
# Default = 1048576 = 1MB (1* 1024 * 1024)
#  allowed_max_file_size: 1048576

# Use pageimages to extend DataObject Page
# To disable the extension for all pages - DataObject Page
# comment out the following:
Page:
  extensions:
    - PageImages

# To enable the extension for Blog pages - DataObject BlogPost
# add the following to mysite/_config/config.yml:
#BlogPost:
#  extensions:
#    - PageImages
